### ISSUE TITLE
ld error when running

### ISSUE THREAD

**Issue by jaccokrijnen** [chrisdone/intero#43] opened 2016-05-24 19:03 UTC
I did the following:

```
jacco@xw4600:~/projects$ git clone https://github.com/chrisdone/intero.git
Cloning into 'intero'...
remote: Counting objects: 413, done.
remote: Compressing objects: 100% (142/142), done.
remote: Total 413 (delta 71), reused 0 (delta 0), pack-reused 271
Receiving objects: 100% (413/413), 224.99 KiB | 0 bytes/s, done.
Resolving deltas: 100% (226/226), done.
Checking connectivity... done.
jacco@xw4600:~/projects$ cd intero/
jacco@xw4600:~/projects/intero$ stack install intero
intero-0.1.8: configure
Configuring intero-0.1.8...
intero-0.1.8: build
Preprocessing executable 'intero' for intero-0.1.8...
[1 of 8] Compiling GhciTypes        ( src/GhciTypes.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/intero/intero-tmp/GhciTypes.o )
[2 of 8] Compiling GhciMonad        ( src/GhciMonad.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/intero/intero-tmp/GhciMonad.o )
[3 of 8] Compiling GhciTags         ( src/GhciTags.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/intero/intero-tmp/GhciTags.o )
[4 of 8] Compiling GhciInfo         ( src/GhciInfo.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/intero/intero-tmp/GhciInfo.o )
[5 of 8] Compiling GhciFind         ( src/GhciFind.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/intero/intero-tmp/GhciFind.o )
[6 of 8] Compiling Paths_intero     ( .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/autogen/Paths_intero.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/intero/intero-tmp/Paths_intero.o )
[7 of 8] Compiling InteractiveUI    ( src/InteractiveUI.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/intero/intero-tmp/InteractiveUI.o )
[8 of 8] Compiling Main             ( src/Main.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/intero/intero-tmp/Main.o )
Linking .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/intero/intero ...
Warning: module not listed in intero.cabal for 'intero' component (add to other-modules): Paths_intero
intero-0.1.8: copy/register
Installing executable(s) in
/home/jacco/projects/intero/.stack-work/install/x86_64-linux/lts-5.16/7.10.3/bin
Copying from /home/jacco/projects/intero/.stack-work/install/x86_64-linux/lts-5.16/7.10.3/bin/intero to /home/jacco/.local/bin/intero

Copied executables to /home/jacco/.local/bin:
- intero
jacco@xw4600:~/projects/intero$ stack ghci --with-ghc intero
The following GHC options are incompatible with GHCi and have not been passed to it: -O2 -threaded
Using main module: 1. Package `intero' component exe:intero with main-is file: /home/jacco/projects/intero/src/Main.hs
Configuring GHCi with the following packages: intero
Intero 0.1.8 (GHC 7.10.3)
Type :intro and press enter for an introduction of the standard commands.

/usr/bin/ld: /home/jacco/projects/intero/.stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/intero/intero-tmp/cbits/hschooks.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/home/jacco/projects/intero/.stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/intero/intero-tmp/cbits/hschooks.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
```

I have the following `ncurses` and `tinfo` libraries
```
jacco@xw4600:~/projects/intero$ dpkg --get-selections | grep ncurses
libncurses5:amd64				install
libncurses5:i386				install
libncurses5-dev:amd64				install
libncursesw5:amd64				install
ncurses-base					install
ncurses-bin					install
jacco@xw4600:~/projects/intero$ dpkg --get-selections | grep tinfo
libtinfo-dev:amd64				install
libtinfo5:amd64					install
libtinfo5:i386					install
```

**Comment by chrisdone** [comment] 2016-05-24 19:32
What about with `--no-load --no-build` to `stack ghci`?

**Comment by mgsloan** [comment] 2016-05-24 19:33
This may well be a dupe of - https://github.com/chrisdone/intero/issues/36

It seems a bit tricky for ghci to load itself.  Maybe try a different repo to test?

**Comment by chrisdone** [comment] 2016-05-24 19:35
@mgsloan That's my experience too. In the past I've been unable to load GHCi within itself. For some reason it works for me at the moment, but it's not surprising that it fails for someone else.

**Comment by jaccokrijnen** [comment] 2016-05-24 20:49
I also tried it with another library (your `ini` package), but I get a different error. 

```
The following GHC options are incompatible with GHCi and have not been passed to it: -O2
Configuring GHCi with the following packages: ini
Intero 0.1.8 (GHC 7.10.3)
Type :intro and press enter for an introduction of the standard commands.

<command line>: can't load .so/.DLL for: libHSghc-prim-0.4.0.0-8TmvWUcS1U1IKHT0levwg3.so (libHSghc-prim-0.4.0.0-8TmvWUcS1U1IKHT0levwg3.so: cannot open shared object file: No such file or directory)
```

By the way,  I'm on Ubuntu 15.10.

**Comment by jaccokrijnen** [comment] 2016-05-24 20:50
I also tried it with another library (your ini package), but I get a different error.

```
The following GHC options are incompatible with GHCi and have not been passed to it: -O2
Configuring GHCi with the following packages: ini
Intero 0.1.8 (GHC 7.10.3)
Type :intro and press enter for an introduction of the standard commands.

<command line>: can't load .so/.DLL for: libHSghc-prim-0.4.0.0-8TmvWUcS1U1IKHT0levwg3.so (libHSghc-prim-0.4.0.0-8TmvWUcS1U1IKHT0levwg3.so: cannot open shared object file: No such file or directory)
```
By the way, I'm on Ubuntu 15.10.

**Comment by jaccokrijnen** [comment] 2016-05-24 20:54
`--no-load` and `--no-build` made no difference.

By the way, I get the same error with just `stack ghci` on the `intero` package (`ini` package does work with normal ghci)

**Comment by chrisdone** [comment] 2016-05-25 07:25
@jaccokrijnen What if you do `stack build intero` within your `ini` project and then run `stack ghci --with-ghc intero` within your `ini` project?

**Comment by jaccokrijnen** [comment] 2016-05-25 09:54
This works! But how/why? I'm not very experienced with stack, but it seems like I am still running the same `intero` executable as before? This `stack build intero` builds the hackage version, right?

**Comment by chrisdone** [comment] 2016-05-25 10:01
@jaccokrijnen I believe it's that when you build Intero it's intended to work with the specific GHC configuration in your stack. I get the same problem if I build Intero (or GHCi-ng) in one LTS and try to use it in a different LTS. Each one should have its own copy. This is good practice because each LTS might be a different GHC version.

When you `stack build foo`, then the executable for `foo` is available when you `stack exec`. Don't install `Intero` globally with `stack install`.

**Comment by jaccokrijnen** [comment] 2016-05-25 10:52
Thanks, that clears things up! I wasn't aware that `stack ghci --with-ghc=...` also searches the lts specific `bin` folder.

**Comment by chrisdone** [comment] 2016-05-31 09:31
I've added a note in the README to be very explicit about using `stack build` and `stack exec`, rather than `stack install`. I've also added a note that looks like this if you launch intero outside of stack:

```
bash-3.2$ $(stack exec which intero)
WARNING: it is HIGHLY RECOMMENDED to use intero with stack:

  To install:
    stack build intero

  To run with no project:
    stack exec intero
  To run with your project:
    stack ghci --with-ghc intero

Intero 0.1.11 (GHC 7.10.3)
Type :intro and press enter for an introduction of the standard commands.

package flags have changed, resetting and loading new packages...
Prelude> :q
Leaving GHCi.
```

**Closed** 2016-05-31 09:30 UTC
Labels: wontfix

**Comment by mgsloan** [comment] 2016-05-31 10:42
It'd be pretty awesome of intero could detect this circumstance and give a better error.

Alternatively, `stack ghci` could also ask ghci for version info and check that.

**Comment by chrisdone** [comment] 2016-05-31 11:24
Actually with some TH we could possibly detect the snapshot that intero was compiled with and then complain if they don't match.

**Comment by mgsloan** [comment] 2016-05-31 11:26
Indeed, that could do it!  However, I think just the ghc version needs to match.  Not 100% sure though

**Comment by chrisdone** [comment] 2016-05-31 11:32
I'll try a repro in a bit. I'm pretty sure I've been using GHC 7.10.3 for everything and still got the problem, but I might be imagining that.

**Comment by jaccokrijnen** [comment] 2016-05-31 11:36
It would be nice if `intero` also kept working for users of `cabal repl` as I'd like to integrate it into `leksah` (which tries to support both cabal-install and stack)

**Comment by fosskers** [comment] 2016-06-06 19:05
For any Arch users wandering in here about `tinfo` linker errors: install [the libtinfo package](https://aur.archlinux.org/packages/libtinfo/) from the AUR.
